---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    allow:
      - dependency-type: all
    schedule:
      interval: weekly
    groups:
      k8s:
        patterns: [ "k8s.io/*", "sigs.k8s.io/*" ]
        update-types: [ "major", "minor", "patch" ]
      containernetworking:
        patterns: [ "github.com/containernetworking/*" ]
      other-go-modules:
        patterns: [ "*" ]
        exclude-patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
          - "github.com/containernetworking/*"
    labels:
      - "dependencies"
      - "go"
  - package-ecosystem: docker
    directories:
      - /
      - /hack
      - /yamls
    schedule:
      interval: weekly
    labels:
      - "dependencies"
      - "docker"
  - package-ecosystem: helm
    directory: /deployment/whereabouts-chart
    schedule:
      interval: weekly
    ignore:
      - dependency-name: ghcr.io/telekom/whereabouts
    labels:
      - "dependencies"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - "dependencies"
      - "ci"
