apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "whereabouts.serviceAccountName" . }}
  labels:
    {{- include "whereabouts.labels" . | nindent 4 }}
rules:
# Preferred/sticky IP: CNI reads pod annotations to determine preferred IP
- apiGroups: [""]
  resources: [pods]
  verbs: [get]
