{{- if .Values.operator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "whereabouts.fullname" . }}-operator-webhook-secret
  {{- include "whereabouts.namespace" . | nindent 2 }}
  labels:
    {{- include "whereabouts.labels" . | nindent 4 }}
rules:
# cert-controller uses a namespace-scoped cache-backed informer to watch the
# webhook TLS Secret for rotation.
- apiGroups: [""]
  resources: [secrets]
  verbs: [create, list, watch]
- apiGroups: [""]
  resources: [secrets]
  resourceNames: [{{ include "whereabouts.fullname" . }}-webhook-cert]
  verbs: [get, update, patch]
{{- end }}
