{{- if .Values.operator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "whereabouts.fullname" . }}-operator-webhook-secret
  {{- include "whereabouts.namespace" . | nindent 2 }}
  labels:
    {{- include "whereabouts.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "whereabouts.fullname" . }}-operator-webhook-secret
subjects:
- kind: ServiceAccount
  name: {{ include "whereabouts.fullname" . }}-operator
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
{{- end }}
