{{- if .Values.webhook.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "whereabouts.fullname" . }}-webhook
  {{- include "whereabouts.namespace" . | nindent 2 }}
  labels:
    {{- include "whereabouts.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "whereabouts.fullname" . }}-webhook
{{- end }}
